#-------------------------------
# General Site Settings
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://veeamkasten.dev" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown
#kramdown:
#   parse_block_html: true 

permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-tabs

paginate: 6
paginate_path: "/page/:num"


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  authors:
    output: true
    permalink: /:name
  demos:
    output: true
    permalink: '/demos'

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "demos"
    values:
      layout: "page"
  

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

callouts_level: loud # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red
